/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import com.openai.client.OpenAIClient;
import com.openai.client.okhttp.OpenAIOkHttpClient;
import com.openai.models.ChatModel;
import com.openai.models.responses.Response;
import com.openai.models.responses.ResponseCreateParams;

public class AiQeCopilot {
    public String getGreeting() {
        return "AI-QE Copilot Started!";
    }

    public static void main(String[] args) {
        System.out.println(new AiQeCopilot().getGreeting());

        OpenAIClient client = OpenAIOkHttpClient.fromEnv();
        ResponseCreateParams params =
        ResponseCreateParams.builder()
                .input("""
    You are a senior Quality Engineer working
    on a regulated banking application.

    Requirement:
    Large international wire transfers require
    additional approval.

    Generate positive, negative and boundary
    test scenarios.

    Do not invent business rules that are not
    stated in the requirement.

    If information required for testing is missing
    or ambiguous, identify it as a clarification
    instead of making an assumption.
    """)
                .model(ChatModel.GPT_5_MINI)
                .build();
        System.out.println("About to call OpenAI...");
        Response response = client.responses().create(params);
        System.out.println("OpenAI call completed...");
        System.out.println(response);
    }
}
