/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import com.openai.models.responses.Response;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.example.model.TestCase;
import org.example.model.TestGenerationResult;

public class AiQeCopilot {

    public static void main(String[] args) throws Exception {

        System.out.println("AI-QE Copilot started!");
        LlmClient llmClient = new LlmClient();
        PromptBuilder promptBuilder = new PromptBuilder();
        String requirement = """
        Customers with expired KYC cannot initiate
        international wire transfers.
        """;
        String prompt = promptBuilder.buildTestGenerationPrompt(requirement);
        System.out.println("PROMPT SENT TO LLM:");
        System.out.println(prompt); 
       
        Response response = llmClient.ask(prompt);
        String json = llmClient.extractText(response);
        ObjectMapper objectMapper = new ObjectMapper();
        TestGenerationResult result =
         objectMapper.readValue(
                json,
                TestGenerationResult.class
        );

        System.out.println("\nGENERATED TEST CASES:");

for (TestCase testCase : result.getTestCases()) {

    System.out.println("--------------------");
    System.out.println("ID: " + testCase.getId());
    System.out.println("Type: " + testCase.getType());
    System.out.println("Scenario: " + testCase.getScenario());
    System.out.println("Expected: " + testCase.getExpectedResult());
    System.out.println("Priority: " + testCase.getPriority());
}

System.out.println("\nCLARIFICATIONS:");

for (String clarification : result.getClarifications()) {
    System.out.println("- " + clarification);
}
//System.out.println("AI GENERATED JSON:");
//System.out.println(json);
       // System.out.println(response);
        //System.out.println("OpenAI call completed...");
    }
}