/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import com.openai.models.responses.Response;

public class AiQeCopilot {

    public static void main(String[] args) {

        System.out.println("AI-QE Copilot started!");
        LlmClient llmClient = new LlmClient();
        PromptBuilder promptBuilder = new PromptBuilder();
        String requirement = """
        Customers with expired KYC cannot initiate
        international wire transfers.
        """;
        String prompt = promptBuilder.buildTestGenerationPrompt(requirement);
        System.out.println("PROMPT SENT TO LLM:");
        System.out.println(prompt); 
       
        Response response = llmClient.ask(prompt);
        System.out.println(response);
        System.out.println("OpenAI call completed...");
    }
}